# Global section
checksum:
  name_template: '{{ .Tag }}-{{ time "20060102" }}-checksums.txt'

snapshot:
  name_template: '{{ .Env.PACKAGE_NAME_PREFIX }}-{{ time "20060102" }}'

release:
  prerelease: auto

changelog:
  filters:
    exclude:
      - '^\[skip changelog\].*'
      - '^\[changelog skip\].*'
      - '^\[skip ci\].*'
      - '^\[ci skip\].*'

# We have multiple builds in order to fine tune
# cross compilations.
builds:
  -
    # OSX
    id: arduino_builder_osx
    binary: arduino-builder
    env:
      - CGO_ENABLED=1
      - CXXFLAGS="-mmacosx-version-min=10.10"
      - CC=/usr/x86_64-apple-darwin14/bin/cc
    goos:
      - darwin
    goarch:
      - amd64
    ldflags:
      - -s -w -X github.com/arduino/arduino-builder/version.versionString={{.Tag}} -X github.com/arduino/arduino-builder/version.commit={{ .ShortCommit }}
  -
    # ARM
    id: arduino_builder_arm
    binary: arduino-builder
    env:
      - CGO_ENABLED=1
      - CC=/usr/arm-linux-gnueabi/bin/cc
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - 6
    ldflags:
      - -s -w -X github.com/arduino/arduino-builder/version.versionString={{.Tag}} -X github.com/arduino/arduino-builder/version.commit={{ .ShortCommit }}
      - "-extldflags '-static'"
  -
    # ARMv7
    id: arduino_builder_armv7
    binary: arduino-builder
    env:
      - CGO_ENABLED=1
      - CC=/usr/arm-linux-gnueabihf/bin/cc
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - 7
    ldflags:
      - -s -w -X github.com/arduino/arduino-builder/version.versionString={{.Tag}} -X github.com/arduino/arduino-builder/version.commit={{ .ShortCommit }}
      - "-extldflags '-static'"
  -
    # ARM64
    id: arduino_builder_arm64
    binary: arduino-builder
    env:
      - CGO_ENABLED=1
      - CC=/usr/aarch64-linux-gnu/bin/cc
    goos:
      - linux
    goarch:
      - arm64
    ldflags:
      - -s -w -X github.com/arduino/arduino-builder/version.versionString={{.Tag}} -X github.com/arduino/arduino-builder/version.commit={{ .ShortCommit }}
      - "-extldflags '-static'"
  -
    # All the other platforms
    id: arduino_builder
    binary: arduino-builder
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - 386
      - mips
      - mipsle
    ldflags:
      - -s -w -X github.com/arduino/arduino-builder/version.versionString={{.Tag}} -X github.com/arduino/arduino-builder/version.commit={{ .ShortCommit }}
      - "-extldflags '-static'"

archives:
  -
    id: "arduino_builder"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    replacements:
      amd64: 64bit
      darwin: macOS
      386: 32bit
      arm: ARM
      arm64: ARM64
      linux: Linux
      windows: Windows
    files:
      - README.md
      - LICENSE.txt

blob:
  -
    provider: s3
    bucket: arduino-downloads-prod-beagle
    ids:
      - arduino_builder
    folder: "{{ .ProjectName }}"
